import Foundation

/// The SDK's identity in `metadata.generator`.
public enum DocuconfSDK {
    public static let name = "docuconf-swift"
    public static let version = "0.1.0"
    public static let language = "swift"
}

/// Writes the contract document (SPEC §4): plain CUE data that unifies with `contract.#Contract`.
public enum Contract {
    /// The contract for a configuration struct.
    ///
    /// - Parameters:
    ///   - name: The service name, a DNS label (`metadata.name`).
    ///   - appVersion: The version or git SHA the contract is exported from.
    ///   - package: The CUE package name. Defaults to `name` with `-` replaced by `_`.
    public static func cue<C: DocuconfConfig>(for type: C.Type, name: String, appVersion: String? = nil, package: String? = nil) throws -> String {
        try cue(for: Declaration(type), name: name, appVersion: appVersion, package: package)
    }

    public static func cue(for declaration: Declaration, name: String, appVersion: String? = nil, package: String? = nil) throws -> String {
        guard isDNSLabel(name) else {
            throw DeclarationError(problems: ["service name \"\(name)\" must be a DNS label ([a-z0-9-], at most 63 characters)"])
        }
        var w = CueWriter()
        w.line("// Code generated by docuconf. DO NOT EDIT.")
        w.line("package \(packageName(package ?? name))")
        w.line("")
        w.line("import \"docuconf.dev/contract\"")
        w.line("")
        w.open("contract.#Contract & {")
        w.field("apiVersion", .string("docuconf.dev/v1alpha1"))
        w.field("kind", .string("ConfigContract"))
        w.open("metadata: {")
        w.field("name", .string(name))
        if let appVersion { w.field("appVersion", .string(appVersion)) }
        w.line("generator: {language: \(JSONValue.quote(DocuconfSDK.language)), sdk: \(JSONValue.quote(DocuconfSDK.name)), version: \(JSONValue.quote(DocuconfSDK.version))}")
        w.close()
        w.open("vars: {")
        for v in declaration.vars.sorted(by: { $0.name < $1.name }) {
            w.open("\(CueWriter.label(v.name)): {")
            for (k, value) in fields(v, overlays: !declaration.overlays.isEmpty) { w.field(k, value) }
            w.close()
        }
        w.close()
        if !declaration.files.isEmpty {
            w.open("files: {")
            for f in declaration.files.sorted(by: { $0.name < $1.name }) {
                w.open("\(CueWriter.label(f.name)): {")
                for (k, value) in fields(f) { w.field(k, value) }
                w.close()
            }
            w.close()
        }
        if !declaration.overlays.isEmpty {
            w.open("overlays: {")
            for o in declaration.overlays.sorted(by: { $0.name < $1.name }) {
                w.open("\(CueWriter.label(o.name)): {")
                for (k, value) in fields(o) { w.field(k, value) }
                w.close()
            }
            w.close()
        }
        w.close()
        return w.text
    }

    /// A variable's contract fields, in a readable order.
    ///
    /// - Parameter overlays: Whether the declaration has config-file overlays. A variable needs a `configKey`
    ///   for the platform to put it in an overlay, so it is then written even when it equals the name. A `json`
    ///   variable gets none: swift-configuration's file snapshots split a nested object into separate keys, so
    ///   the app could not read it back from an overlay, and without a `configKey` the platform keeps it in
    ///   the environment.
    public static func fields(_ v: VarSpec, overlays: Bool = false) -> [(String, JSONValue)] {
        var out: [(String, JSONValue)] = [("type", .string(v.type.rawValue)), ("description", .string(v.description))]
        if v.required { out.append(("required", true)) }
        if v.secret { out.append(("secret", true)) }
        if let g = v.group { out.append(("group", .string(g))) }
        if let e = v.examples { out.append(("examples", .array(e.map(JSONValue.string)))) }
        if let d = v.deprecated { out.append(("deprecated", deprecation(d))) }
        if overlays ? v.type != .json : v.key != v.name { out.append(("configKey", .string(v.key))) }
        switch v.type {
        case .string:
            if let x = v.minLength { out.append(("minLength", .int(x))) }
            if let x = v.maxLength { out.append(("maxLength", .int(x))) }
            if let x = v.pattern { out.append(("pattern", .string(x))) }
        case .int, .float:
            if let x = v.min { out.append(("min", x.json)) }
            if let x = v.max { out.append(("max", x.json)) }
        case .duration:
            out.append(("encoding", .string(v.durationWire.rawValue)))
            if let x = v.minDuration { out.append(("min", .string(GoDuration.format(x)))) }
            if let x = v.maxDuration { out.append(("max", .string(GoDuration.format(x)))) }
        case .url:
            if let x = v.schemes { out.append(("schemes", .array(x.map(JSONValue.string)))) }
        case .enum:
            out.append(("values", .array((v.values ?? []).map(JSONValue.string))))
        case .list:
            out.append(("items", .string((v.items ?? .string).rawValue)))
            out.append(("encoding", .string(v.listWire.rawValue)))
            if v.listWire == .csv && v.separator != "," { out.append(("separator", .string(v.separator))) }
            if let x = v.minItems { out.append(("minItems", .int(x))) }
            if let x = v.maxItems { out.append(("maxItems", .int(x))) }
            if let x = v.itemMin { out.append(("itemMin", .int(x))) }
            if let x = v.itemMax { out.append(("itemMax", .int(x))) }
        case .json:
            if let s = v.schema { out.append(("schema", s)) }
        case .bool:
            break
        }
        if let d = v.defaultValue, !v.secret, !v.required { out.append(("default", d)) }
        return out
    }

    /// A file input's contract fields, in a readable order.
    public static func fields(_ f: FileSpec) -> [(String, JSONValue)] {
        var out: [(String, JSONValue)] = [("type", .string(f.type.rawValue))]
        if f.type == .config, let fmt = f.format { out.append(("format", .string(fmt.rawValue))) }
        if f.type == .keystore { out.append(("format", .string((f.keystoreFormat ?? .pkcs12).rawValue))) }
        out.append(("description", .string(f.description)))
        if f.required { out.append(("required", true)) }
        if f.secret { out.append(("secret", true)) }
        out.append(("path", .string(f.path)))
        if let p = f.pathEnv { out.append(("pathEnv", .string(p))) }
        if f.reload != .restart { out.append(("reload", .string(f.reload.rawValue))) }
        if let m = f.maxSize { out.append(("maxSize", .int(m))) }
        if let g = f.group { out.append(("group", .string(g))) }
        if let d = f.deprecated { out.append(("deprecated", deprecation(d))) }
        switch f.type {
        case .config:
            if let s = f.schema { out.append(("schema", s)) }
        case .tls:
            if let d = f.dnsNames { out.append(("dnsNames", .array(d.map(JSONValue.string)))) }
            if let k = f.keyAlgorithms { out.append(("keyAlgorithms", .array(k.map { .string($0.rawValue) }))) }
            if let m = f.minRemaining { out.append(("minRemaining", .string(GoDuration.format(m)))) }
            if f.requireCA { out.append(("requireCA", true)) }
        case .caBundle:
            if let m = f.minCertificates { out.append(("minCertificates", .int(m))) }
        case .keystore:
            if let p = f.passwordVar { out.append(("passwordVar", .string(p))) }
        case .text:
            if let p = f.pattern { out.append(("pattern", .string(p))) }
            if let m = f.minLength { out.append(("minLength", .int(m))) }
            if let m = f.maxLength { out.append(("maxLength", .int(m))) }
        case .binary:
            break
        }
        return out
    }

    /// An overlay's contract fields (`#Overlay`), in a readable order.
    public static func fields(_ o: ConfigOverlay) -> [(String, JSONValue)] {
        var out: [(String, JSONValue)] = []
        if let d = o.description { out.append(("description", .string(d))) }
        out.append(("format", .string(o.format.rawValue)))
        out.append(("path", .string(o.path)))
        out.append(("keySeparator", .string(o.keySeparator)))
        out.append(("reload", .string(o.reload.rawValue)))
        return out
    }

    static func deprecation(_ d: Deprecation) -> JSONValue {
        var o: [(String, JSONValue)] = [("message", .string(d.message))]
        if let r = d.replacedBy { o.append(("replacedBy", .string(r))) }
        return .object(o)
    }

    static func isDNSLabel(_ s: String) -> Bool {
        let chars = Array(s.unicodeScalars)
        guard (1...63).contains(chars.count) else { return false }
        let ok: (Unicode.Scalar) -> Bool = { ("a"..."z").contains($0) || ("0"..."9").contains($0) }
        return ok(chars.first!) && ok(chars.last!) && chars.allSatisfy { ok($0) || $0 == "-" }
    }

    static func packageName(_ s: String) -> String {
        var p = String(s.map { $0.isLetter || $0.isNumber || $0 == "_" ? $0 : "_" })
        if p.first.map({ !$0.isLetter }) ?? true { p = "c" + p }
        return p
    }
}

/// Emits CUE with tab indentation.
struct CueWriter {
    private(set) var text = ""
    private var depth = 0

    mutating func line(_ s: String) {
        text += (s.isEmpty ? "" : String(repeating: "\t", count: depth) + s) + "\n"
    }

    mutating func open(_ s: String) {
        line(s)
        depth += 1
    }

    mutating func close() {
        depth -= 1
        line("}")
    }

    mutating func field(_ key: String, _ value: JSONValue) {
        switch value {
        case .object(let members) where !members.isEmpty:
            open("\(Self.label(key)): {")
            for (k, v) in members { field(k, v) }
            close()
        case .array(let items) where items.contains(where: Self.isComposite):
            open("\(Self.label(key)): [")
            for item in items { element(item) }
            depth -= 1
            line("]")
        default:
            line("\(Self.label(key)): \(Self.inline(value))")
        }
    }

    private mutating func element(_ value: JSONValue) {
        switch value {
        case .object(let members) where !members.isEmpty:
            open("{")
            for (k, v) in members { field(k, v) }
            depth -= 1
            line("},")
        default:
            line(Self.inline(value) + ",")
        }
    }

    static func isComposite(_ v: JSONValue) -> Bool {
        switch v {
        case .object(let m): !m.isEmpty
        case .array(let a): a.contains(where: isComposite)
        default: false
        }
    }

    static func inline(_ v: JSONValue) -> String {
        switch v {
        case .null: "null"
        case .bool(let b): b ? "true" : "false"
        case .int(let i): String(i)
        case .double(let d): JSONValue.format(d)
        case .string(let s): JSONValue.quote(s)
        case .array(let a): "[" + a.map(inline).joined(separator: ", ") + "]"
        case .object(let o): o.isEmpty ? "{}" : "{" + o.map { "\(label($0.0)): \(inline($0.1))" }.joined(separator: ", ") + "}"
        }
    }

    static let keywords: Set<String> = ["package", "import", "for", "in", "if", "let", "true", "false", "null", "div", "mod", "quo", "rem"]

    /// A field label: bare when it is a plain identifier, quoted otherwise.
    static func label(_ s: String) -> String {
        let scalars = Array(s.unicodeScalars)
        let isIdent = !scalars.isEmpty
            && (("a"..."z").contains(scalars[0]) || ("A"..."Z").contains(scalars[0]))
            && scalars.allSatisfy { ("a"..."z").contains($0) || ("A"..."Z").contains($0) || ("0"..."9").contains($0) || $0 == "_" }
        return isIdent && !keywords.contains(s) ? s : JSONValue.quote(s)
    }
}
