import CueTestSupport
import DocuconfCore
import Foundation
import Testing

@Suite struct ExportTests {
    static let goldenURL = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("Golden/gateway.cue")

    func export() throws -> String {
        try Contract.cue(for: GatewayConfig.self, name: "gateway", appVersion: "1.4.0")
    }

    @Test func matchesGolden() throws {
        let text = try export()
        if ProcessInfo.processInfo.environment["DOCUCONF_UPDATE_GOLDEN"] == "1" {
            try text.write(to: Self.goldenURL, atomically: true, encoding: .utf8)
        }
        let golden = try String(contentsOf: Self.goldenURL, encoding: .utf8)
        #expect(text == golden, "export differs from Golden/gateway.cue; rerun with DOCUCONF_UPDATE_GOLDEN=1 and review the diff")
    }

    @Test func isDeterministic() throws {
        #expect(try export() == export())
    }

    @Test func passesCueVet() throws {
        let outcome = try CueVet.vet(export(), package: "gateway")
        switch outcome {
        case .passed: break
        case .failed(let output): Issue.record("cue vet failed:\n\(output)")
        case .skipped(let why):
            if CueVet.required { Issue.record("cue vet required but skipped: \(why)") }
        }
    }

    @Test func minimalContractPassesCueVet() throws {
        struct Minimal: DocuconfConfig {
            @Env("port", "HTTP listen port") var port = 8080
        }
        let text = try Contract.cue(for: Minimal.self, name: "minimal")
        #expect(!text.contains("files:"))
        if case .failed(let output) = try CueVet.vet(text, package: "minimal") { Issue.record("cue vet failed:\n\(output)") }
    }

    struct RunLimits: JSONConfigValue { var max: Int }

    @Test func lengthLimitsPassCueVet() throws {
        struct Lengths: DocuconfConfig {
            @Env("callback.url", "Where to report the run", .schemes("https"), .maxLength(40))
            var callback = URL(string: "https://ledger.example.com/runs/callback")!
            @Env("limits", "Run limits as JSON", .maxLength(16)) var limits = RunLimits(max: 12_345_678)
            @Env("branches", "Branch codes", .items(1...8), .itemLength(2...4)) var branches = ["ZÜ01", "BE", "GE02"]
        }
        let text = try Contract.cue(for: Lengths.self, name: "lengths")
        #expect(text.contains("itemMinLength: 2") && text.contains("itemMaxLength: 4"))
        if case .failed(let output) = try CueVet.vet(text, package: "lengths") { Issue.record("cue vet failed:\n\(output)") }
        // The meta-schema checks the new fields: item lengths on an int list are rejected.
        let bad = text
            .replacingOccurrences(of: #""ZÜ01",\s*"BE",\s*"GE02""#, with: "1", options: .regularExpression)
            .replacingOccurrences(of: #"items:(\s+)"string""#, with: #"items:$1"int""#, options: .regularExpression)
        #expect(bad.contains(#""int""#) && !bad.contains("ZÜ01"))
        if case .passed = try CueVet.vet(bad, package: "lengths") { Issue.record("cue vet accepted item lengths on an int list") }
    }

    @Test func headerPackageAndImport() throws {
        let lines = try export().split(separator: "\n", omittingEmptySubsequences: false)
        #expect(lines[0] == "// Code generated by docuconf. DO NOT EDIT.")
        #expect(lines[1] == "package gateway")
        #expect(lines[3] == "import \"docuconf.dev/contract\"")
        #expect(lines[5] == "contract.#Contract & {")
    }

    @Test func varsAndFilesAreSorted() throws {
        let d = try Declaration(GatewayConfig.self)
        let text = try export()
        let varOrder = d.vars.map(\.name).sorted().map { text.range(of: "\t\t\($0): {")!.lowerBound }
        #expect(varOrder == varOrder.sorted())
        let fileOrder = d.files.map(\.name).sorted().map { name -> String.Index in
            let label = name.contains("-") ? "\"\(name)\"" : name
            return text.range(of: "\t\t\(label): {")!.lowerBound
        }
        #expect(fileOrder == fileOrder.sorted())
    }

    @Test func secretsCarryNoDefaultOrExample() throws {
        let d = try Declaration(GatewayConfig.self)
        for v in d.vars where v.secret {
            let fields = Contract.fields(v).map(\.0)
            #expect(!fields.contains("default"))
            #expect(!fields.contains("examples"))
        }
    }

    @Test func invalidServiceName() {
        #expect(throws: DeclarationError.self) { try Contract.cue(for: GatewayConfig.self, name: "Gateway_API") }
    }

    @Test func exportIsData() throws {
        // `cue export` turns the contract into JSON: it is plain data, as SPEC §4 requires.
        guard let json = try CueVet.export(export()) else { return }
        let value = try JSONDecoder().decode(JSONValue.self, from: Data(json.utf8))
        #expect(value["metadata"]?["generator"]?["language"] == "swift")
        #expect(value["vars"]?["REQUEST_TIMEOUT"]?["default"] == "30s")
        #expect(value["vars"]?["REQUEST_TIMEOUT"]?["max"] == "5m")
        #expect(value["vars"]?["HTTP_PORT"]?["configKey"] == "http.port")
        #expect(value["files"]?["serving-tls"]?["minRemaining"] == "720h")
        #expect(value["files"]?["routes"]?["schema"]?["required"] == ["items"])
    }
}
