// Code generated by docuconf. DO NOT EDIT.
package gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "gateway"
		appVersion: "1.4.0"
		generator: {language: "swift", sdk: "docuconf-swift", version: "0.1.0"}
	}
	vars: {
		API_TOKEN: {
			type: "string"
			description: "Token for the partner API"
			required: true
			secret: true
			configKey: "api.token"
			minLength: 16
			maxLength: 128
			pattern: "^[A-Za-z0-9_-]+$"
		}
		CLOUD_REGION: {
			type: "string"
			description: "Cloud region the gateway runs in"
			group: "cloud"
			examples: ["eu-west-1", "us-east-2"]
			configKey: "cloud.region"
			pattern: "^[a-z]+-[a-z]+-[0-9]$"
			default: "eu-west-1"
		}
		DATABASE_URL: {
			type: "url"
			description: "Primary Postgres connection string"
			required: true
			secret: true
			group: "database"
			configKey: "database.url"
			schemes: ["postgres", "postgresql"]
		}
		HTTP_PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "http.port"
			min: 1
			max: 65535
			default: 8080
		}
		KAFKA_BROKERS: {
			type: "list"
			description: "Kafka brokers to connect to"
			configKey: "kafka.brokers"
			items: "string"
			encoding: "csv"
			minItems: 1
			maxItems: 5
			default: ["kafka-0:9092", "kafka-1:9092"]
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum log level"
			configKey: "log.level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		OTEL_ENDPOINT: {
			type: "url"
			description: "OTLP endpoint; tracing export is off when unset"
			configKey: "otel.endpoint"
			schemes: ["http", "https"]
		}
		PARTNER_KEYSTORE_PASSWORD: {
			type: "string"
			description: "Password for the partner keystore"
			required: true
			secret: true
			configKey: "partner.keystorePassword"
		}
		RATE_LIMIT: {
			type: "json"
			description: "Per-client rate limit"
			configKey: "rate.limit"
			schema: {
				type: "object"
				properties: {
					requestsPerSecond: {
						type: "integer"
					}
					burst: {
						type: "integer"
					}
					exempt: {
						type: "array"
						items: {
							type: "string"
						}
					}
				}
				required: ["requestsPerSecond", "burst"]
			}
			default: {
				burst: 200
				requestsPerSecond: 100
			}
		}
		REQUEST_TIMEOUT: {
			type: "duration"
			description: "Upstream request timeout"
			details: "The gateway gives up on an upstream after this long and answers 504. Raise it for slow batch\nendpoints; keep it below the load balancer's idle timeout, see `LoadBalancer/idleTimeout`.\n\n# Choosing a value\n\n- p99 latency, from `upstream_seconds`\n- retries\n\n```promql\nhistogram_quantile(0.99, upstream_seconds_bucket)\n```\n\n**Note:** Read in seconds."
			configKey: "request.timeout"
			encoding: "seconds"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		RETRY_BACKOFF_MS: {
			type: "list"
			description: "Retry backoff steps in milliseconds"
			configKey: "retry.backoffMs"
			items: "int"
			encoding: "csv"
			maxItems: 10
		}
		RETRY_WEIGHTS: {
			type: "list"
			description: "Relative weight of each retry step"
			configKey: "retry.weights"
			items: "int"
			encoding: "csv"
			itemMin: -2147483648
			itemMax: 2147483647
		}
		SAMPLING_RATIO: {
			type: "float"
			description: "Fraction of requests to trace"
			configKey: "sampling.ratio"
			min: 0.0
			max: 1.0
			default: 0.25
		}
		SHARD_IDS: {
			type: "list"
			description: "Shard ids this instance owns"
			configKey: "shard.ids"
			items: "int"
			encoding: "csv"
			itemMin: 0
			itemMax: 1023
			default: [0]
		}
		TRACING_ENABLED: {
			type: "bool"
			description: "Whether to export traces"
			configKey: "tracing.enabled"
			default: false
		}
		UPSTREAM_TIMEOUT: {
			type: "duration"
			description: "Old name for the upstream timeout"
			deprecated: {
				message: "Use REQUEST_TIMEOUT"
				replacedBy: "REQUEST_TIMEOUT"
			}
			configKey: "upstream.timeout"
			encoding: "seconds"
		}
	}
	files: {
		geoip: {
			type: "binary"
			description: "GeoIP database"
			path: "/etc/gateway/geoip/GeoLite2-City.mmdb"
			maxSize: 100000000
		}
		license: {
			type: "text"
			description: "Licence key"
			required: true
			secret: true
			path: "/etc/gateway/license/license.key"
			pattern: "^[A-Z0-9-]{8,}\\n?$"
		}
		partner: {
			type: "keystore"
			format: "pkcs12"
			description: "Client certificate for the partner API"
			secret: true
			path: "/etc/gateway/partner/keystore.p12"
			passwordVar: "PARTNER_KEYSTORE_PASSWORD"
		}
		routes: {
			type: "config"
			format: "json"
			description: "Routing table: path prefixes and their upstreams"
			details: "Each route maps a path prefix to an upstream URL.\n\nThe longest prefix wins."
			required: true
			path: "/etc/gateway/routes/routes.json"
			pathEnv: "ROUTES_FILE"
			reload: "watch"
			maxSize: 65536
			schema: {
				type: "object"
				properties: {
					items: {
						type: "array"
						items: {
							type: "object"
							properties: {
								match: {
									type: "string"
								}
								upstream: {
									type: "string"
									format: "uri"
								}
								methods: {
									type: "array"
									items: {
										type: "string"
									}
								}
								timeoutSeconds: {
									type: "number"
								}
							}
							required: ["match", "upstream"]
						}
					}
					fallback: {
						type: "string"
						format: "uri"
					}
				}
				required: ["items"]
			}
		}
		"serving-tls": {
			type: "tls"
			description: "Certificate the gateway serves HTTPS with"
			required: true
			secret: true
			path: "/etc/gateway/tls"
			reload: "watch"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
			requireCA: true
		}
		settings: {
			type: "config"
			format: "yaml"
			description: "Currency, limits and strictness"
			path: "/etc/gateway/settings/settings.yaml"
			schema: {
				type: "object"
				properties: {
					currency: {
						type: "string"
						enum: ["EUR", "USD"]
					}
					limits: {
						type: "object"
						additionalProperties: {
							type: "integer"
						}
					}
					flags: {
						type: "object"
						properties: {
							strict: {
								type: "boolean"
							}
						}
						required: ["strict"]
					}
				}
				required: ["currency", "limits", "flags"]
			}
		}
		"trusted-cas": {
			type: "caBundle"
			description: "Private CAs to trust for upstream calls"
			path: "/etc/gateway/ca/bundle.pem"
			pathEnv: "SSL_CERT_FILE"
			minCertificates: 2
		}
	}
}
