// Code generated by docuconf. DO NOT EDIT.
package gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "gateway"
		generator: {language: "swift", sdk: "docuconf-swift", version: "0.1.0"}
	}
	vars: {
		DATABASE_URL: {
			type: "url"
			description: "Primary Postgres connection string"
			required: true
			secret: true
			configKey: "database.url"
			schemes: ["postgres", "postgresql"]
		}
		HTTP_PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "http.port"
			min: 1
			max: 65535
			default: 8443
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum log level"
			configKey: "log.level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		REQUEST_TIMEOUT: {
			type: "duration"
			description: "Upstream request timeout"
			configKey: "request.timeout"
			encoding: "seconds"
			min: "1s"
			max: "5m"
			default: "30s"
		}
	}
	files: {
		routes: {
			type: "config"
			format: "json"
			description: "Routing table: path prefixes and their upstreams"
			required: true
			path: "/etc/gateway/routes/routes.json"
			reload: "watch"
			schema: {
				type: "object"
				properties: {
					routes: {
						type: "array"
						items: {
							type: "object"
							properties: {
								prefix: {
									type: "string"
								}
								upstream: {
									type: "string"
									format: "uri"
								}
							}
							required: ["prefix", "upstream"]
						}
					}
				}
				required: ["routes"]
			}
		}
		tls: {
			type: "tls"
			description: "Certificate the gateway serves HTTPS with"
			secret: true
			path: "/etc/gateway/tls"
			dnsNames: ["gateway.internal"]
			minRemaining: "168h"
		}
	}
}
